apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multisnake-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "multisnake-ip"
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: multisnake-frontend
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multisnake-server-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "multisnake-ip-server"
    kubernetes.io/ingress.class: "gce"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/connection-proxy-header: "upgrade"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: multisnake-server
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: multisnake-server
            port:
              number: 8001