apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multisnake-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "multisnake-ip"
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.websocket-backend: "true"
    kubernetes.io/ingress.timeout-sec: "3600"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: multisnake-frontend
            port:
              number: 80
      - path: /ws/game
        pathType: Prefix
        backend:
          service:
            name: multisnake-server
            port:
              number: 8000
      - path: /ws/controller
        pathType: Prefix
        backend:
          service:
            name: multisnake-server
            port:
              number: 8001