apiVersion: apps/v1
kind: Deployment
metadata:
  name: multisnake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multisnake
  template:
    metadata:
      labels:
        app: multisnake
    spec:
      containers:
      - name: multisnake-frontend
        image: europe-west1-docker.pkg.dev/cloudcomputing-446812/multisnake/multisnake-frontend
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
      - name: multisnake-server
        image: europe-west1-docker.pkg.dev/cloudcomputing-446812/multisnake/multisnake-server
        ports:
        - containerPort: 8000
        - containerPort: 8001
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: multisnake-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: multisnake
---
apiVersion: v1
kind: Service
metadata:
  name: multisnake-server
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    name: frontend-port
  - port: 8001
    targetPort: 8001
    name: controller-port
  selector:
    app: multisnake